import { Fugaz_One, Open_Sans } from 'next/font/google';
import './globals.css';

const opensans = Open_Sans({
  subsets: ['latin'],
});

const fugaz = Fugaz_One({
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata = {
  title: 'MindfulMe',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const header = (
    <header className="p-4 sm:p-8 flex items-center justify-between gap-4">
      <h1 className={`text-base sm:text-lg textGradient  ${fugaz.className}`}>
        MindfulMe
      </h1>

      <div className="flex items-center justify-between">Placehoder....</div>
    </header>
  );

  const footer = (
    <foot className="p-4 sm:p-8 grid place-items-center">
      <p className={`text-indigo-400 ${fugaz.className}`}>Created with ❤️ </p>
    </foot>
  );

  return (
    <html lang="en">
      <body
        className={`${opensans.className} w-full max-w-[1000px] mx-auto text-sm sm:text-base min-h-screen flex flex-col text-slate-700`}
      >
        <header>{header}</header>
        <main className="flex-1">{children}</main>
        <footer className="p-4">{footer}</footer>
      </body>
    </html>
  );
}
